version: "3"

volumes:
    node_data: {}

services:
    server:
        image: node:16.1.0-alpine
        container_name: nodejs
        expose:
            - 5000
        environment:
            - WSDL_URL=https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl
        restart: on-failure
        deploy:
            restart_policy:
                condition: on-failure
        ports:
            - 5000:5000
        volumes:
            - "./:/home/app/"
        command: sh -c "cd /home/app && npm install --save && npm run start"
