swagger: "2.0"
info:
  description: '<font size="2" color="red">MIT Licença</font>'
  version: "1.0.3"
  title: "Web Scraping Api"
  license:
    name: "REST TO SOAP"
    url: "https://github.com/lucioerlan"
host: "localhost:5000"
basePath: "/api"
schemes:
  - "http"
paths:
  /consultZip:
    post:
      tags:
        - "ROUTES"
      summary: "Consult Zip"
      description: "List complete addresses passing the zip code as parameter"
      operationId: "consult_zip"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Example 69914366"
          required: true
          schema:
            $ref: "#/definitions/correio"
      responses:
        default:
          description: "successful operation"

definitions:
  correio:
    type: "object"
    required:
      - "cep"
    properties:
      cep:
        type: "integer"
